
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
use_frameworks!

target 'LearnSwift' do
    pod 'RxSwift', '~> 5.1.1'
    pod 'RxCocoa', '~> 5.1.1'
    pod 'RxDataSources', '~> 4.0.1'
    pod 'RxAlamofire'
end

